[package]
name = "vcp-cli"
description = "VCP SDK command-line interface"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
vcp-core = { path = "../vcp-core" }
clap = { version = "4", features = ["derive"] }
serde_json = "1"
